### ISSUE TITLE
Change license for run-time hooks

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4810]
Follow-up to https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/1:

* New run-time hooks shall become Apache-2.0
* Existing run-time hooks shall become Apache-2.0, too.

**Todo**
- [x] Add APL- Licence text to the repo
- [x] Add resp. section to COPYING.txt
- [x] Create list of all authors who contributed to run-time hooks
- [x] Write e-mail to all these authors and ask for agreement.
- [x] If some authors do not answer (e.g. since they vanished like xiovat), check whether they still have code in the run-time hook.
- [x] Update license header for those run-time hooks we have an agreement for.

**Rational:**

Strictly speaking the "Bootloader-exception" only applies to the bootloader, not the run-time hooks, which go into the frozen package. We might need a new license which states this.

For the runtime-hooks I suggest to port the principle of the "Bootloader-exception" to the run-time hooks: to be used without restrictions even in your proprietary program. Reading the GPL FAQ, I suggest to use the Apache License 2.0 for the run-time hooks:

Rational:
* Creating a new licence is to much effort.
* LGPL is not appropriate: [Section 4 for the LGPL](https://www.gnu.org/licenses/lgpl-3.0.html#section4) requires the application to include a copy of the LGPL licence and to enable the user to replace the LGPL-ed code (the run-time hook) by a different (modified) version of that code. This is neither practical nor what the "Bootloader-exception" means.
* The FSE [recommends using APL for short works](https://www.gnu.org/licenses/gpl-faq.html#WhatIfWorkIsShort), which terms to prevent contributors and distributors from suing for patent infringement.

**Comment by Legorooj** [comment]
@htgoebel https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/1#issuecomment-613864979 is related. Also, see pyinstaller/pyinstaller-hooks-contrib#2

**Comment by Legorooj** [comment]
@htgoebel can we have a "live" list of all the people that answered "yes"? I need to know for #4822, so I can remove and relicense runtime hooks that are moving into hooks-contrib.

**Comment by Legorooj** [comment]
Just to help, here's a list of the hooks and authors we need permission from first - the ones that are being moved to contrib. I've added their usernames, but not tagged them.

### Hooks

* `nltk`
* `certifi`
* `enchant` - this hook (well the version we have currently, which is a total rewrite) was only authored by @matysek who's said relicensing is ok.
* `gtk`
* `osgeo` - We've already contacted the developer, in #1528 
* `usb`

### Authors

* `brightening-eyes`
* `ktong`
* `virtuald`
* `itszero`

**Comment by Legorooj** [comment]
As per an email, I'm tagging these authors to get their permission. The names may be wrong, but I don't think so.

* @leycec 
* @bpteague 
* @guimas are you `gsmatti`? I thought you might be based on the fact that https://github.com/hydroffice/hyo_bagexplorer/commit/7e039f40976b46d8f862bcf027736a71fa5647ee has your profile photo on it.
* @thiolliere 
* @duploduplo 
* @KenjiTakahashi 

If any of you have contributed to PyInstaller at any point - those of you who work for develer might have done so through Giovanno Bajo - and have contributed to runtime hooks, are you ok with this license change? Please let us know. If you haven't contributed, please let us know. If you aren't ok with this, let us know.

**Comment by thiolliere** [comment]
I agree to put my work on py-installer on the license APL

**Comment by KenjiTakahashi** [comment]
Yes, I am fine with the change. Cheers!

**Comment by duploduplo** [comment]
I am fine with the changes.

Cheers,
Lorenzo/duploduplo

**Comment by bpteague** [comment]
Fine by me!  Thanks for checking, and for all your hard work on PyInstaller (:

**Comment by htgoebel** [comment]
guimas/gmasetti agreed in https://github.com/pyinstaller/pyinstaller/pull/1528#issuecomment-617271635
