### ISSUE TITLE
tracking issue: modulegraph -> modulegraph2

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#5812]
This is a tracking issue to update the internal API to be compatible with modulegraph2.

- [ ]  `run_script` -> `add_script`
- [ ]  `createReference` -> `add_edge`
- [ ]  `findNode` -> `find_node`
- [ ]  `flatten` -> `iter_graph`
- [ ]  `getReferences` -> `outgoing`

**Comment by Avasam** [comment]
> - BaseNode needs to have a code object (awaiting https://github.com/ronaldoussoren/modulegraph2/pull/17)

Just noting an answer from the maintainer: https://github.com/ronaldoussoren/modulegraph2/pull/17#issuecomment-1367211123
> It has been a while since I looked at modulegraph2 in earnest, but it seems that this PR is no longer necessary because I added a code attribute to the nodes where a code object can be relevant in version 2.2.
